networks:
  solarwatch:  

services:
  db:
    container_name: db-solar-watch-app
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MyPassword!"
    networks:
      - solarwatch
      
  solar-watch:
    container_name: api-solar-watch-app
    image: solar-watch:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MSSQL_CONNECTION=Server=db-solar-watch-app;Database=SolarWatchApi;User Id=sa;Password=MyPassword!;Encrypt=false;
    networks:
      - solarwatch

